debug: true
# 调试模式
# 性能影响: 一般

data-section:
  fixed-mode: NORMAL
  val-mode: NORMAL
  var-mode: NORMAL
  # 量替换模式
  # DISABLE: 完全禁用所有
  # NORMAL: 不允许变量嵌套
  # UNIVERSAL: 替换直到无变量，可以嵌套变量
  # 性能影响: 较小

attribute:
  engine: INTERNAL
  # INTERNAL内置属性引擎
  # 如果你不把 Sertraline 与 其他属性插件一起使用，推荐值: INTERNAL
  # 可选: INTERNAL,MYTHIC_LIB,ATTRIBUTE_PLUS,MYTHIC_MOBS,SX_ATTRIBUTE_2,SX_ATTRIBUTE_3，必须选择现有的插件的类型
  # 性能影响: 因选择而异
  default: INTERNAL
  # 默认属性使用
  # 如果你不把 Sertraline 与 其他属性插件一起使用，推荐值以及所有带有属性的物品的属性部分使用的类型: INTERNAL
  # 可选: INTERNAL,MMOITEMS,ATTRIBUTE_PLUS,MYTHIC_MOBS,SX_ATTRIBUTE_2,SX_ATTRIBUTE_3，必须选择现有的插件的类型
  # 性能影响: 因选择而异