debug: true
# 调试模式
# 性能影响: 一般

attribute:
  debounce-time: 500
  # 状态刷新防抖函数执行频率，单位毫秒
  # 表示应在玩家最后一次移动物品等刷新属性后的多长时间后计算属性

  # 例如:
  # 触发刷新属性条件
  # 在500ms内 再次 触发刷新属性条件, 500ms计时重置
  # 自上次触发刷新条件的 500 ms 后
  # 刷新属性

  # 将此数值调低可避免属性计算不及时，但可能会影响性能
  # 默认值: 500 性能影响: 一般
  # 详情见 https://taboolib.feishu.cn/wiki/C2oDwYpa7i9AyykaiKMc3PbNndu

  default: MYTHIC_LIB
  # 默认属性使用，默认 MYTHIC_LIB，本插件需要 MYTHIC_LIB。
  # 如果你不把 Sertraline 与 其他属性插件一起使用，推荐值以及所有带有属性的物品的属性部分使用的类型: MYTHIC_LIB
  # 可选: MYTHIC_LIB,ATTRIBUTE_PLUS,MYTHIC_MOBS,SX_ATTRIBUTE_2,SX_ATTRIBUTE_3，必须选择现有的插件的类型
  # 性能影响: 因选择而异

  default-definer: sertraline_<slot>
  # 默认属性注册关键字。

  require-enabled-slot:
    - HELMET
    - CHESTPLATE
    - LEGGINGS
    - BOOTS
    - ANY_HAND
  # 刷新属性时哪些格子的物品会被遍历。不推荐修改。
  # 默认遍历 所有装备 + 副手 + 主手
  # 性能影响: 一般

action:
  throttle-time: 200
  # action刷新节流函数执行频率，单位毫秒
  # 表示应在玩家执行相同种类的action后的多长时间冷却才可继续执行相同的action

  # 例如:
  # 玩家右键 // 执行
  # 玩家右键 // 不会执行
  # 玩家右键 // 不会执行
  # 自上次成功执行的 200 ms 后
  # 玩家右键 // 执行

  # 将此数值调低可避免action计算不及时，但可能会影响性能
  # 默认值: 200 性能影响: 一般
  # 详情见 https://taboolib.feishu.cn/wiki/C2oDwYpa7i9AyykaiKMc3PbNndu

  require-enabled-slot:
    - HELMET
    - CHESTPLATE
    - LEGGINGS
    - BOOTS
    - ANY_HAND
  # 刷新属性时哪些格子的物品会执行。不推荐修改。
  # 默认遍历 所有装备 + 副手 + 主手
  # 性能影响: 较小