debug: false
# Debug Mode
# Performance impact: Normal

lang: en_US
# Language

database:
  type: SQLITE # SQLITE or MYSQL
  mysql:
    host: needy.girl.overdose
    port: 22127
    user: raincandy_u
    password: angelkawaii2
    database: sertraline
# Not enabled yet!