debug: true
# 调试模式
# 性能影响: 中

attribute:
  debounce-time: 500
  # 状态刷新防抖函数执行频率，单位毫秒
  # 表示应在玩家最后一次移动物品等刷新属性后的多长时间后计算属性
  # 例如玩家移动物品后，在500ms内再移动一次不会计算属性，在最后一次移动后的500ms才会计算。
  # 将此数值调低可避免属性计算不及时，但可能会影响性能
  # 默认值: 500
  kether-amount: true
  # 对 Amount 数值进行 Kether 解析
  # 性能影响: 一般
  default: MYTHIC_LIB
  # 默认属性使用，默认 MYTHIC_LIB，本插件需要 MYTHIC_LIB。
  # 如果你不把 Sertraline 与 其他属性插件一起使用，推荐值以及所有带有属性的物品的属性部分使用的类型: MYTHIC_LIB
  # 可选: MYTHIC_LIB,ATTRIBUTE_PLUS,MYTHIC_MOBS,SX_ATTRIBUTE_2,SX_ATTRIBUTE_3，必须选择现有的插件的类型
  # 性能影响: 因选择而异
  default-definer: sertraline_<slot>
  # 默认属性注册关键字。
  require-enabled-slot:
    - HELMET
    - CHESTPLATE
    - LEGGINGS
    - BOOTS
    - ANY_HAND
  # 刷新属性时哪些格子的物品会被遍历。不推荐修改。
  # 默认遍历 所有装备 + 副手 + 主手
  # 性能影响: 一般

action:
  require-enabled-slot:
    - HELMET
    - CHESTPLATE
    - LEGGINGS
    - BOOTS
    - ANY_HAND
  # 刷新属性时哪些格子的物品会执行。不推荐修改。
  # 默认遍历 所有装备 + 副手 + 主手
  # 性能影响: 较小